export const EVENT_TYPE_KEYWORDS: [string, string][] = [
  ['aircon', 'maintenance'],
  ['compressor', 'maintenance'],
  ['out of order', 'maintenance'],
  ['保险箱', 'maintenance'],
  ['safe', 'maintenance'],
  ['leak', 'facilities'],
  ['drip', 'facilities'],
  ['deposit', 'deposit_issue'],
  ['no-show', 'no_show'],
  ['no show', 'no_show'],
  ['wifi', 'complaint'],
  ['noise', 'complaint'],
  ['complain', 'complaint'],
  ['check-in', 'check_in'],
  ['checked in', 'check_in'],
  ['check in', 'check_in'],
  ['passport', 'compliance'],
  ['immigration', 'compliance'],
  ['护照', 'compliance'],
  ['coffee machine', 'note'],
  ['parcel', 'note'],
  ['door ajar', 'note'],
  ['not slept in', 'note'],
];
